// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fk4peace/golang_services/blog/internal/service (interfaces: iAuthStorage)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock/AuthStorage.go -mock_names=iAuthStorage=AuthStorage . iAuthStorage
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// AuthStorage is a mock of iAuthStorage interface.
type AuthStorage struct {
	ctrl     *gomock.Controller
	recorder *AuthStorageMockRecorder
	isgomock struct{}
}

// AuthStorageMockRecorder is the mock recorder for AuthStorage.
type AuthStorageMockRecorder struct {
	mock *AuthStorage
}

// NewAuthStorage creates a new mock instance.
func NewAuthStorage(ctrl *gomock.Controller) *AuthStorage {
	mock := &AuthStorage{ctrl: ctrl}
	mock.recorder = &AuthStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AuthStorage) EXPECT() *AuthStorageMockRecorder {
	return m.recorder
}

// GetPersonRolesById mocks base method.
func (m *AuthStorage) GetPersonRolesById(personId int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonRolesById", personId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonRolesById indicates an expected call of GetPersonRolesById.
func (mr *AuthStorageMockRecorder) GetPersonRolesById(personId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonRolesById", reflect.TypeOf((*AuthStorage)(nil).GetPersonRolesById), personId)
}
