// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fk4peace/golang_services/blog/internal/service (interfaces: iPostsStorage)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock/PostsStorage.go -mock_names=iPostsStorage=PostsStorage . iPostsStorage
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/fk4peace/golang_services/blog/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// PostsStorage is a mock of iPostsStorage interface.
type PostsStorage struct {
	ctrl     *gomock.Controller
	recorder *PostsStorageMockRecorder
	isgomock struct{}
}

// PostsStorageMockRecorder is the mock recorder for PostsStorage.
type PostsStorageMockRecorder struct {
	mock *PostsStorage
}

// NewPostsStorage creates a new mock instance.
func NewPostsStorage(ctrl *gomock.Controller) *PostsStorage {
	mock := &PostsStorage{ctrl: ctrl}
	mock.recorder = &PostsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PostsStorage) EXPECT() *PostsStorageMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *PostsStorage) CreatePost(personId int64, content string) (*entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", personId, content)
	ret0, _ := ret[0].(*entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *PostsStorageMockRecorder) CreatePost(personId, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*PostsStorage)(nil).CreatePost), personId, content)
}

// GetPostById mocks base method.
func (m *PostsStorage) GetPostById(postId int64) (*entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostById", postId)
	ret0, _ := ret[0].(*entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostById indicates an expected call of GetPostById.
func (mr *PostsStorageMockRecorder) GetPostById(postId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostById", reflect.TypeOf((*PostsStorage)(nil).GetPostById), postId)
}

// GetPosts mocks base method.
func (m *PostsStorage) GetPosts(limit, page int64) ([]entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", limit, page)
	ret0, _ := ret[0].([]entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *PostsStorageMockRecorder) GetPosts(limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*PostsStorage)(nil).GetPosts), limit, page)
}

// GetPostsTotal mocks base method.
func (m *PostsStorage) GetPostsTotal() (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsTotal")
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsTotal indicates an expected call of GetPostsTotal.
func (mr *PostsStorageMockRecorder) GetPostsTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsTotal", reflect.TypeOf((*PostsStorage)(nil).GetPostsTotal))
}
